.TH "compmode_reg_u" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compmode_reg_u \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ade7880_registers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBreg_all\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint16_t \fBTERMSEL1_0\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBTERMSEL1_1\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBTERMSEL1_2\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBTERMSEL2_0\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBTERMSEL2_1\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBTERMSEL2_2\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBTERMSEL3_0\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBTERMSEL3_1\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBTERMSEL3_2\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBANGLESEL\fP:2"
.br
.ti -1c
.RI "   uint16_t \fBVNOMAEN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBVNOMBEN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBVNOMCEN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBSELFREQ\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBRESERVED\fP:2"
.br
.ti -1c
.RI "} \fBbits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 238 of file ade7880_registers\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ANGLESEL"

.PP
Definition at line 252 of file ade7880_registers\&.h\&.
.SS "struct { \&.\&.\&. }  bits"

.SS "uint16_t reg_all"

.PP
Definition at line 240 of file ade7880_registers\&.h\&.
.SS "uint16_t RESERVED"

.PP
Definition at line 257 of file ade7880_registers\&.h\&.
.SS "uint16_t SELFREQ"

.PP
Definition at line 256 of file ade7880_registers\&.h\&.
.SS "uint16_t TERMSEL1_0"

.PP
Definition at line 243 of file ade7880_registers\&.h\&.
.SS "uint16_t TERMSEL1_1"

.PP
Definition at line 244 of file ade7880_registers\&.h\&.
.SS "uint16_t TERMSEL1_2"

.PP
Definition at line 245 of file ade7880_registers\&.h\&.
.SS "uint16_t TERMSEL2_0"

.PP
Definition at line 246 of file ade7880_registers\&.h\&.
.SS "uint16_t TERMSEL2_1"

.PP
Definition at line 247 of file ade7880_registers\&.h\&.
.SS "uint16_t TERMSEL2_2"

.PP
Definition at line 248 of file ade7880_registers\&.h\&.
.SS "uint16_t TERMSEL3_0"

.PP
Definition at line 249 of file ade7880_registers\&.h\&.
.SS "uint16_t TERMSEL3_1"

.PP
Definition at line 250 of file ade7880_registers\&.h\&.
.SS "uint16_t TERMSEL3_2"

.PP
Definition at line 251 of file ade7880_registers\&.h\&.
.SS "uint16_t VNOMAEN"

.PP
Definition at line 253 of file ade7880_registers\&.h\&.
.SS "uint16_t VNOMBEN"

.PP
Definition at line 254 of file ade7880_registers\&.h\&.
.SS "uint16_t VNOMCEN"

.PP
Definition at line 255 of file ade7880_registers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMS from the source code\&.
