.TH "config2_reg_u" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config2_reg_u \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ade7880_registers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBreg_all\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBEXTREFEN\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBI2C_LOCK\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBRESERVED\fP:6"
.br
.ti -1c
.RI "} \fBbits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 109 of file ade7880_registers\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. }  bits"

.SS "uint8_t EXTREFEN"

.PP
Definition at line 114 of file ade7880_registers\&.h\&.
.SS "uint8_t I2C_LOCK"

.PP
Definition at line 115 of file ade7880_registers\&.h\&.
.SS "uint8_t reg_all"

.PP
Definition at line 111 of file ade7880_registers\&.h\&.
.SS "uint8_t RESERVED"

.PP
Definition at line 116 of file ade7880_registers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMS from the source code\&.
