DEVICE_CONFIGERATION
NAME
DEVICE_CONFIGERATION -
Functions
int8_t config_cmd (uint32_t cmd, uint8_t arg,...)
.PP
 "
int8_t ade7880_power_mode (uint8_t mode)
.PP
 "
int8_t ade7880_config_reg_default ()
.PP
 "
int8_t spi_init (uint8_t chip_select)
.PP
 "
int8_t rpi_gpio_init (void)
.PP
 "
Detailed Description
DEVICE CONFIGERATION
The module contains functions that are prepared and used to configure the
 Raspberry pi GPIO and spi interface, As well as ADE7880 Power mode,
 Serial Port selection (that is SPI port activation) and Default configuration
 procedure as described in the device datasheet section QUICK SETUP AS ENERGY METER.
ADE7880 SPI PORT ACTIVATION
TOGEL SS PIN 3 TIMES or execute three SPI write operations to a location in the address space that is not allocated to a specific register
Write to CONFIG2 register to lock the port.
POWER MODE SELECTION
 The ADE7880 has four modes of operation, determined by the state of the PM0 and PM1 pins
ADE7880 DEFAULT CONFIGERATION
 This is a procedure adapted from the device datasheet section QUICK SETUP AS ENERGY METER based on the application.
Configer gain registers
Initialize WTHR, VARTHR, VATHR, VLEVEL and VNOM registers based Equation 26, Equation 37, Equation 44, Equation 22, and Equation 42, respectively, Please see the datasheet
 ADE7880 http://www.analog.com/static/imported-files/data_sheets/ADE7880.pdf.
Enable the data memory RAM protection, by writing 0xAD to an internal 8-bit register located
 at Address 0xE7FE, followed by a write of 0x80 to an internal 8-bit register located at Address 0xE7E3.
Start the DSP by setting Run = 1.
Function Documentation
int8_t ade7880_config_reg_default (void)
 configure ADE7880 as 3-Phase, 4-Wire, Wye Distribution Systems energy meter
 with the default values .
function return 0 or -1, on success or failure respectively .
Referenced by main(), and reading_loop().
int8_t ade7880_power_mode (uint8_tmode)
 Parameters:
mode indicates the selected power mode
Function to set up power mode of ADE7880.
function return 0 or -1, on success or failure respectively.
Referenced by main().
int8_t config_cmd (uint32_tcmd, uint8_targ, ...)
 Parameters:
cmd Indicates specific configuration procedure to be execute
arg Additional argument to control the execution
... argument list attachment that is required by the procedure to be executed
Function runs the selected configuration procedure on ADE7880.
Returns:
function return 0 or -1, on success or failure respectively.
Referenced by main(), and wait_new_conversion().
int8_t rpi_gpio_init (void)
 configure used Rpi gpio pins. Pins used by the spi, will be setup up when
 the module is initialized.
Returns:
function return 0 or -1, on success or failure respectively.
Definition at line 63 of file rpi_hwio.c.
References PIN_IRQ0, PIN_IRQ1, PIN_PM0, PIN_PM1, and PIN_SS.
Referenced by main().
                          {
    
        bcm2835_gpio_fsel(PIN_SS, BCM2835_GPIO_FSEL_OUTP);
        bcm2835_gpio_fsel(PIN_PM0, BCM2835_GPIO_FSEL_OUTP);
        bcm2835_gpio_fsel(PIN_PM1, BCM2835_GPIO_FSEL_OUTP);
        bcm2835_gpio_fsel(PIN_IRQ0, BCM2835_GPIO_FSEL_INPT);
        bcm2835_gpio_fsel(PIN_IRQ1, BCM2835_GPIO_FSEL_INPT);
            
return 0;
}
int8_t spi_init (uint8_tchip_select)
 Parameters:
chip_select Indicates the selected chip for communication
function initializ the Rpi SPI interfce.
Returns:
function return 0 or -1, on success or failure respectively.
Definition at line 38 of file rpi_hwio.c.
Referenced by main(), and spi_rd_wr().
                                    {
    
    bcm2835_spi_begin();
    bcm2835_spi_setBitOrder(BCM2835_SPI_BIT_ORDER_MSBFIRST);
    bcm2835_spi_setDataMode(BCM2835_SPI_MODE0); // Data are propagated on a falling edge
                                                                
    bcm2835_spi_setClockDivider(BCM2835_SPI_CLOCK_DIVIDER_256); // 65536 = 262.144us = 3.814697260kHz
    bcm2835_spi_chipSelect(chip_select);
    bcm2835_spi_setChipSelectPolarity(chip_select, LOW); // SS/HSA chip pin of ade7880 should be low for comminication
return 0;
}
Author
Generated automatically by Doxygen for EMS from the source code.