.TH "DEVICE_CONFIGERATION" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DEVICE_CONFIGERATION \- 
.PP
.PP
.PP
.PP
  

.SS "Functions"

.in +1c
.ti -1c
.RI "int8_t \fBconfig_cmd\fP (uint32_t cmd, uint8_t arg,\&.\&.\&.)"
.br
.RI "\fI.PP
 \fP"
.ti -1c
.RI "int8_t \fBade7880_power_mode\fP (uint8_t mode)"
.br
.RI "\fI.PP
 \fP"
.ti -1c
.RI "int8_t \fBade7880_config_reg_default\fP ()"
.br
.RI "\fI.PP
 \fP"
.in -1c
.in +1c
.ti -1c
.RI "int8_t \fBspi_init\fP (uint8_t chip_select)"
.br
.RI "\fI.PP
 \fP"
.in -1c
.in +1c
.ti -1c
.RI "int8_t \fBrpi_gpio_init\fP (void)"
.br
.RI "\fI.PP
 \fP"
.in -1c
.SH "Detailed Description"
.PP 
.PP
.PP
.PP
 

DEVICE CONFIGERATION
The module contains functions that are prepared and used to configure the 
.br
 Raspberry pi GPIO and spi interface, As well as ADE7880 Power mode, 
.br
 Serial Port selection (that is SPI port activation) and Default configuration 
.br
 procedure as described in the device datasheet section QUICK SETUP AS ENERGY METER\&.
.PP

.br
.PP
\fIADE7880\fP SPI PORT ACTIVATION 
.br
 
.PD 0

.IP "\(bu" 2
TOGEL SS PIN 3 TIMES or execute three SPI write operations to a location in the address space that is not allocated to a specific register 
.IP "\(bu" 2
Write to CONFIG2 register to lock the port\&.
.PP
\fIPOWER\fP MODE SELECTION 
.br
 The ADE7880 has four modes of operation, determined by the state of the PM0 and PM1 pins  
.PP
\fIADE7880\fP DEFAULT CONFIGERATION 
.br
 This is a procedure adapted from the device datasheet section QUICK SETUP AS ENERGY METER based on the application\&. 
.PD 0

.IP "\(bu" 2
Configer gain registers 
.IP "\(bu" 2
Initialize WTHR, VARTHR, VATHR, VLEVEL and VNOM registers based Equation 26, Equation 37, Equation 44, Equation 22, and Equation 42, respectively, Please see the datasheet 
.br
 \fBADE7880\fP http://www.analog.com/static/imported-files/data_sheets/ADE7880.pdf\&. 
.IP "\(bu" 2
Enable the data memory RAM protection, by writing 0xAD to an internal 8-bit register located 
.br
 at Address 0xE7FE, followed by a write of 0x80 to an internal 8-bit register located at Address 0xE7E3\&.
.PP
.PD 0
.IP "\(bu" 2
Start the DSP by setting Run = 1\&. 
.PP

.SH "Function Documentation"
.PP 
.SS "int8_t ade7880_config_reg_default (void)"

.PP
.PP
 configure ADE7880 as 3-Phase, 4-Wire, Wye Distribution Systems energy meter 
.br
 with the default values \&.
.PP
.SS "function return 0 or -1, on success or failure respectively \&."

.PP
Referenced by main(), and reading_loop()\&.
.SS "int8_t ade7880_power_mode (uint8_tmode)"

.PP
.PP
 \fBParameters:\fP
.RS 4
\fImode\fP indicates the selected power mode
.RE
.PP
Function to set up power mode of ADE7880\&.
.PP
.SS "function return 0 or -1, on success or failure respectively\&."

.PP
Referenced by main()\&.
.SS "int8_t config_cmd (uint32_tcmd, uint8_targ, \&.\&.\&.)"

.PP
.PP
 \fBParameters:\fP
.RS 4
\fIcmd\fP Indicates specific configuration procedure to be execute 
.br
\fIarg\fP Additional argument to control the execution 
.br
\fI\&.\&.\&.\fP argument list attachment that is required by the procedure to be executed
.RE
.PP
Function runs the selected configuration procedure on ADE7880\&.
.PP
\fBReturns:\fP
.RS 4
function return 0 or -1, on success or failure respectively\&. 
.PP
 
.RE
.PP

.PP
Referenced by main(), and wait_new_conversion()\&.
.SS "int8_t rpi_gpio_init (void)"

.PP
.PP
 configure used Rpi gpio pins\&. Pins used by the spi, will be setup up when 
.br
 the module is initialized\&.
.PP
\fBReturns:\fP
.RS 4
function return 0 or -1, on success or failure respectively\&. 
.PP
 
.RE
.PP

.PP
Definition at line 63 of file rpi_hwio\&.c\&.
.PP
References PIN_IRQ0, PIN_IRQ1, PIN_PM0, PIN_PM1, and PIN_SS\&.
.PP
Referenced by main()\&.
.PP
.nf
63                           {
64     
65         bcm2835_gpio_fsel(PIN_SS,  BCM2835_GPIO_FSEL_OUTP);
66         bcm2835_gpio_fsel(PIN_PM0,  BCM2835_GPIO_FSEL_OUTP);
67         bcm2835_gpio_fsel(PIN_PM1,  BCM2835_GPIO_FSEL_OUTP);
68         bcm2835_gpio_fsel(PIN_IRQ0, BCM2835_GPIO_FSEL_INPT);
69         bcm2835_gpio_fsel(PIN_IRQ1, BCM2835_GPIO_FSEL_INPT);
70             
71 return 0;   
72 }
.fi
.SS "int8_t spi_init (uint8_tchip_select)"

.PP
.PP
 \fBParameters:\fP
.RS 4
\fIchip_select\fP Indicates the selected chip for communication
.RE
.PP
function initializ the Rpi SPI interfce\&.
.PP
\fBReturns:\fP
.RS 4
function return 0 or -1, on success or failure respectively\&. 
.PP
 
.RE
.PP

.PP
Definition at line 38 of file rpi_hwio\&.c\&.
.PP
Referenced by main(), and spi_rd_wr()\&.
.PP
.nf
38                                     {
39     
40     bcm2835_spi_begin();
41     bcm2835_spi_setBitOrder(BCM2835_SPI_BIT_ORDER_MSBFIRST);    
42     bcm2835_spi_setDataMode(BCM2835_SPI_MODE0);                     // Data are propagated on a falling edge 
43                                                                 
44     bcm2835_spi_setClockDivider(BCM2835_SPI_CLOCK_DIVIDER_256);     // 65536 = 262\&.144us = 3\&.814697260kHz 
45     bcm2835_spi_chipSelect(chip_select);                                            
46     bcm2835_spi_setChipSelectPolarity(chip_select, LOW);            // SS/HSA chip pin of ade7880 should be low for comminication      
47 
48 return 0;   
49 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for EMS from the source code\&.
