.TH "lcycmode_reg_u" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lcycmode_reg_u \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ade7880_registers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBreg_all\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBLWATT\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBLVAR\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBLVA\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBZXSEL_A\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBZXSEL_B\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBZXSEL_C\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBRSTREAD\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBPFMODE\fP:1"
.br
.ti -1c
.RI "} \fBbits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 198 of file ade7880_registers\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. }  bits"

.SS "uint8_t LVA"

.PP
Definition at line 205 of file ade7880_registers\&.h\&.
.SS "uint8_t LVAR"

.PP
Definition at line 204 of file ade7880_registers\&.h\&.
.SS "uint8_t LWATT"

.PP
Definition at line 203 of file ade7880_registers\&.h\&.
.SS "uint8_t PFMODE"

.PP
Definition at line 210 of file ade7880_registers\&.h\&.
.SS "uint8_t reg_all"

.PP
Definition at line 200 of file ade7880_registers\&.h\&.
.SS "uint8_t RSTREAD"

.PP
Definition at line 209 of file ade7880_registers\&.h\&.
.SS "uint8_t ZXSEL_A"

.PP
Definition at line 206 of file ade7880_registers\&.h\&.
.SS "uint8_t ZXSEL_B"

.PP
Definition at line 207 of file ade7880_registers\&.h\&.
.SS "uint8_t ZXSEL_C"

.PP
Definition at line 208 of file ade7880_registers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMS from the source code\&.
