.TH "p1" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p1 \- IMPORTANT MACROS 
.PD 0
.IP "\(bu" 2
\fICALIBRATION\fP CONSTANTS: This constants calculated so that readings fetched from target registers 
.br
 can be converted into meaningful values such as amps , volts, kwh, watt\&. 
.br
 The constants should be adjusted if there is any change to Hardware design 
.br
 The calibration steps can be found from this \fBcalibration\fP document 
.br
 http://www.analog.com/static/imported-files/application_notes/AN-1171.pdf \&. 
.br
 
.PP
\fBNote:\fP
.RS 4
Since all phases on the meter are matched, the same constant can be used 
.br
 for all energy, power,current rms and voltage rms readings on any Rpi
.RE
.PP
.PP
.nf
VLSB_CONST              211184.71337579617834394904458599        LSB constant for voltage reading 24 volt max is assumed
ILSB_CONST              353022.88732394                          LSB constant for current reading 30 Amp max is assumed
WHLSB_CONST             (67.28)*2.275                            LSB constant for energy reading
WATTLSB_CONST           8505                                     LSB constant for power reading  .fi
.PP

.PP
.PD 0
.IP "\(bu" 2
\fITRANSFORMER_RATIO\fP 
.br
 This value is the ratio of the voltage transformer 
.br
 used to step down the line voltage to lower level\&. the value should be adjusted if different transformer is used\&. 
.PP
.nf
  TRANSFORMER_RATIO         20.56621005
.fi
.PP

.PP
.PD 0
.IP "\(bu" 2
\fICONFIGURATION\fP COMMANDS This macros determine the common configuration file 
.br
 between the phyton script and this software\&. And the 
.br
 configuration command structure\&. 
.br
 You only need to adjust this values, to obtain the 
.br
 corresponding changes on the program execution\&. 
.PP
.nf
 CONFIG_FILE_NAME       "config.csv"            defines configuration           
 CONFIG_CMD_FORMAT      "%hd %s %lu %hhu %hhu"  configuration command format specifier

.fi
.PP
 
.PP

