.TH "phase_data_t" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phase_data_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <includes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBIRMS\fP"
.br
.ti -1c
.RI "float \fBVRMS\fP"
.br
.ti -1c
.RI "float \fBWH\fP"
.br
.ti -1c
.RI "float \fBPOWER\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file includes\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float IRMS"

.PP
Definition at line 17 of file includes\&.h\&.
.PP
Referenced by reading_loop(), and save_to_file()\&.
.SS "float POWER"

.PP
Definition at line 20 of file includes\&.h\&.
.PP
Referenced by reading_loop(), and save_to_file()\&.
.SS "float VRMS"

.PP
Definition at line 18 of file includes\&.h\&.
.PP
Referenced by reading_loop(), and save_to_file()\&.
.SS "float WH"

.PP
Definition at line 19 of file includes\&.h\&.
.PP
Referenced by reading_loop(), and save_to_file()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMS from the source code\&.
