.TH "phsign_reg_u" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phsign_reg_u \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ade7880_registers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBreg_all\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint16_t \fBAWSIGN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBBWSIGN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBCWSIGN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBSUM1SIGN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBAFVARSIGN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBBFVARSIGN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBCFVARSIGN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBSUM2SIGN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBSUM3SIGN\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBRESERVED\fP:7"
.br
.ti -1c
.RI "} \fBbits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 151 of file ade7880_registers\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t AFVARSIGN"

.PP
Definition at line 160 of file ade7880_registers\&.h\&.
.SS "uint16_t AWSIGN"

.PP
Definition at line 156 of file ade7880_registers\&.h\&.
.SS "uint16_t BFVARSIGN"

.PP
Definition at line 161 of file ade7880_registers\&.h\&.
.SS "struct { \&.\&.\&. }  bits"

.SS "uint16_t BWSIGN"

.PP
Definition at line 157 of file ade7880_registers\&.h\&.
.SS "uint16_t CFVARSIGN"

.PP
Definition at line 162 of file ade7880_registers\&.h\&.
.SS "uint16_t CWSIGN"

.PP
Definition at line 158 of file ade7880_registers\&.h\&.
.SS "uint16_t reg_all"

.PP
Definition at line 153 of file ade7880_registers\&.h\&.
.SS "uint16_t RESERVED"

.PP
Definition at line 165 of file ade7880_registers\&.h\&.
.SS "uint16_t SUM1SIGN"

.PP
Definition at line 159 of file ade7880_registers\&.h\&.
.SS "uint16_t SUM2SIGN"

.PP
Definition at line 163 of file ade7880_registers\&.h\&.
.SS "uint16_t SUM3SIGN"

.PP
Definition at line 164 of file ade7880_registers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMS from the source code\&.
