.TH "rpi_hwio.c" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rpi_hwio.c \- 
.PP
\fIFile:\fP \fBrpi_hwio\&.c\fP 
.br
  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./includes/includes\&.h'\fP
.br

.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "int8_t \fBspi_init\fP (uint8_t chip_select)"
.br
.RI "\fI.PP
 \fP"
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "int8_t \fBrpi_gpio_init\fP (void)"
.br
.RI "\fI.PP
 \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
\fIFile:\fP \fBrpi_hwio\&.c\fP 
.br
 

\fIPurpose:\fP 
.br
 
.PP
Definition in file \fBrpi_hwio\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EMS from the source code\&.
