SERIAL_INTERFACE
NAME
SERIAL_INTERFACE -
int8_t spi_rd_wr (uint8_t chip_select, uint8_t *tx_buffer, uint16_t len)
.PP
 "
uint32_t spi_read (uint8_t chip_select, uint8_t chip_address, uint16_t target_register, uint8_t reg_len)
.PP
 "
int8_t spi_write (uint8_t chip_select, uint8_t chip_address, uint16_t target_register, int32_t value, uint8_t reg_len)
int8_t spi_ram_protection (uint8_t cmd, uint8_t chip_address)
.PP
 "
Detailed Description
SERIAL INTERFACE
spi driver application layer, The module handles the data transfer between the Rpi and ADE7880":
The ADE7880 is always a slave of the communication
The maximum serial clock frequency supported by this interface is 2.5 MHz
SPI Read Operation procedure
The read operation initiated when SS/HSA pin is set to low and begins sending one byte,
 representing the address of the chip , on the MOSI line.
 Notice:(Bit 0 of the address byte must be 1 for a read operation)
Next, 16-bit address of the register that is read will be sent.
Then ADE7880 after it receives the last bit of address of the register on a low-to-high
 transition of SCLK, it begins to transmit its contents on the MISO line when the next
 SCLK high-to-low transition occurs;
After the last bit is received, set the SS and SCLK lines high and the communication ends.
The data lines, MOSI and MISO, go into a high impedance state.
Please see the datasheet ADE7880 http://www.analog.com/static/imported-files/data_sheets/ADE7880.pdf for more details.
SPI Wirte Operation procedure
The write operation initiated when SS/HSA pin is set to low and begins sending one byte,
 representing the address of the chip , on the MOSI line.
 Notice:(Bit 0 of the address byte must be 0 for a read operation)
Next, 16-bit address of the register that is written will be sent.
And then without losing any SCLK cycle, the 32-, 16-, or 8-bit value will be sent
After the last bit is received, set the SS and SCLK lines high and the communication ends.
The data lines, MOSI and MISO, go into a high impedance state.
Please see the datasheet ADE7880 http://www.analog.com/static/imported-files/data_sheets/ADE7880.pdf for more details.
Function Documentation
int8_t spi_ram_protection (uint8_tcmd, uint8_tchip_address)
 Parameters:
cmd protection enable/disable command
chip_select Indicates the selected chip for communication
Function runs RAM protection enable or disable procedure on ADE7880
 the function also verifies the communication by reading the
 LAST OPERATION,LAST ADDRESS and LAST READ WRITE DATA registers and
 outputs message to console if there is a failure.
Returns:
function return 0 or -1, on success or failure respectively .
Definition at line 343 of file spi_ade7880_protocol.c.
References address_byte_ut::address_all, ade7880_ram_lock_msg_ut::address_byte, ADE7880_WR, address_byte_ut::bits, CHIP_ADDRESS1, DISABLE, ENABLE, LAST_ADD, LAST_OP, LAST_RWDATA8, RAM_LOCK_MSG_LENGTH, address_byte_ut::RD_WR, spi_read(), value, and ade7880_ram_lock_msg_ut::value.
                                                           {
      
      
    int8_t result = 0;
    
    uint8_t value = (cmd==ENABLE)?0x80:0x00;
    
     ade7880_ram_lock_msg_ut tx_buff_1st_msg,tx_buff_2nd_msg;
     tx_buff_1st_msg.msg_fields.address_byte.address_all = chip_address;
     tx_buff_1st_msg.msg_fields.address_byte.bits.RD_WR = ADE7880_WR;
     tx_buff_1st_msg.msg_fields.target_register = htons(0xE7FE);
     tx_buff_1st_msg.msg_fields.value = 0xAD;
     
     
     tx_buff_2nd_msg.msg_fields.address_byte.address_all = chip_address;
     tx_buff_2nd_msg.msg_fields.address_byte.bits.RD_WR = ADE7880_WR;
     tx_buff_2nd_msg.msg_fields.target_register = htons(0xE7E3);
     tx_buff_2nd_msg.msg_fields.value = value;
     
    #ifdef DEBUG
       if(debug_print&0x01){
       printf('\nMSG SENT: WR\n');
       printf(' Chip Address %02X\n',
       tx_buff_1st_msg.msg_fields.address_byte.address_all);
       printf(' 1st Target Register %04X\n',
       ntohs(tx_buff_1st_msg.msg_fields.target_register)
       );
       printf(' Value sent 1st %1X\n',
       ntohl(tx_buff_1st_msg.msg_fields.value));
       
       printf(' 2nd Target Register %04X\n',
       ntohs(tx_buff_2nd_msg.msg_fields.target_register)
       );
       printf(' Value sent %01X\n',
       ntohl(tx_buff_2nd_msg.msg_fields.value));
       }
    #endif
    
    bcm2835_spi_transfern(tx_buff_1st_msg.msg_all,RAM_LOCK_MSG_LENGTH);
    bcm2835_spi_transfern(tx_buff_2nd_msg.msg_all,RAM_LOCK_MSG_LENGTH);
    
    uint8_t result8 =0;
    uint16_t result16 =0;
    
     #ifdef DEBUG
     if(!(debug_print&0x80))
     debug_print = DISABLE;
       printf('\nvarifying last operation ...\n');
     #endif
     if((result8 =(uint8_t)(spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,LAST_OP,sizeof(uint16_t))))
     !=0xCA /*LAST_OP!=WR*/){
             
     #ifdef DEBUG
       printf('\n <--- WR failure : LAST_OP \n');
       printf(' LAST_OP value :%02X\n',result8);
     #endif
     result = -1;
     }else{
      #ifdef DEBUG
       printf(' LAST_OP value :%02X\n',result8);
     #endif
     }
     
     #ifdef DEBUG
       printf('\nvarifying last accessed register ...\n');
     #endif
     if((result16 =(uint16_t)(spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,LAST_ADD,sizeof(uint16_t))))!=0xE7E3){
             
     #ifdef DEBUG
       printf('\n <--- WR failure : LAST_ADD\n');
       printf(' Target Register :%04X\n', 0xE7E3);
       printf(' LAST_ADD value :%04X\n',result16);
     #endif
     result = -1;
     }else{
      #ifdef DEBUG
        printf(' LAST_ADD value :%04X\n',result16);
      #endif
     }
     
    
     #ifdef DEBUG
       printf('\nvarifying last accessed register value:\n');
     #endif
     result8 = (uint8_t)(spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,LAST_RWDATA8,sizeof(uint8_t))&0x000000FF);
    
     if(result8!=value)
         result = -1;
     #ifdef DEBUG
       if(result8!=value)
       printf('\n <--- WR failure : LAST_RWDATA\n');
       printf(' Sent Value :%01X\n', value);
       printf(' LAST_RWDATA value :%01X\n',result8);
       
       if(!(debug_print&0x80))
           debug_print = ENABLE;
     #endif
     
     
    return result;
}
int8_t spi_rd_wr (uint8_tchip_select, uint8_t *tx_buffer, uint16_tlen)
 Parameters:
chip_select Indicates the selected chip for communication
tx_buffer Pointer to transmit buffer
len length of the data
initalizes spi of RPi , sends out data from tx_buffer and also receive back data into rc_buffer and end spi to return the normal gpio functionality.
Returns:
function return 0 or -1, on success or failure respectively.
Definition at line 114 of file spi_ade7880_protocol.c.
References PIN_SS, and spi_init().
{
   
       
       if(!spi_init(chip_select)){
    
          bcm2835_spi_transfern(tx_buffer,sizeof(tx_buffer));
          return 0;
       }else
          return -1;
    
       bcm2835_spi_end();
       
       bcm2835_gpio_write(PIN_SS, HIGH);
}
uint32_t spi_read (uint8_tchip_select, uint8_tchip_address, uint16_ttarget_register, uint8_treg_len)
 Parameters:
chip_select Indicates the selected chip for communication
chip_address the chip address or id of the used ADE7880
target_register the address of the register to read from
reg_len the size of the register in byte
reads the specified register value from the selected ade7880 chip, according to the recommended SPI read Operation procedure, see the device datasheet for more detail.
Returns:
function return ther resulting value on success and on failure 0x0F000000.
Parameters:
chip_select Indicates the selected chip for communication
chip_address the chip address or id of the used ADE7880
target_register the address of the register to update
value value to be written
reg_len the size of the register in byte
update the specified register value on the selected ade7880 chip
 according to the recommended SPI write Operation procedure,
 see the device datasheet for more detail
 the function will also verify the communication by reading the
 LAST OPERATION,LAST ADDRESS and LAST READ WRITE DATA registers and
 outputs message to console if there is a failure.
Remarks:
the function dosen't consider 24bit signed value regisers on the device,
 if it become necessory to wright to regisers of this kind remember to modify.
Returns:
function return 0 or -1, on success or failure respectively .
Definition at line 147 of file spi_ade7880_protocol.c.
References address_byte_ut::address_all, ade7880_read_tx_buff_ut::address_byte, ADE7880_RD, address_byte_ut::bits, DUMMY_MSG, RD_MSG_LENGTH, address_byte_ut::RD_WR, ade7880_read_tx_buff_ut::reg16, ade7880_read_tx_buff_ut::reg32, and ade7880_read_tx_buff_ut::reg8.
Referenced by main(), measure(), spi_ram_protection(), spi_write(), and wait_new_conversion().
                                                                                                    {
   
  uint32_t result= 0;
    ade7880_read_tx_buff_ut tx_buff;
    
    tx_buff.msg_fields.address_byte.address_all = chip_address;
    tx_buff.msg_fields.address_byte.bits.RD_WR = ADE7880_RD;
    tx_buff.msg_fields.target_register = htons(target_register);
    tx_buff.msg_fields.value.reg32 = DUMMY_MSG;
    #ifdef DEBUG
     if((debug_print&0x01)){
       printf('\nMSG SENT : RD\n');
       
       printf(' Chip Address %02X\n',tx_buff.msg_fields.address_byte.address_all);
       printf(' Target Register %04X\n',ntohs(tx_buff.msg_fields.target_register));
       printf(' DUMMY %08X \n',tx_buff.msg_fields.value.reg32);
       }
    #endif
    
    bcm2835_spi_transfern(tx_buff.msg_all,RD_MSG_LENGTH + reg_len);
    
    
              
    
    
    
    result = (reg_len == sizeof(uint32_t))?((uint32_t)ntohl(tx_buff.msg_fields.value.reg32))
             :((reg_len == sizeof(uint16_t))?((uint32_t)ntohs(tx_buff.msg_fields.value.reg16))
             :((reg_len == sizeof(uint8_t))?((uint32_t)tx_buff.msg_fields.value.reg8):0x0F000000/*ERROR*/));
    
    
    #ifdef DEBUG
     if(debug_print&0x01 || 1){
       printf('\nMSG REPLAY : RD\n');
       printf(' REPLAY :%X\n',result);
     }
    #endif
    
    
    return result;
    
}
int8_t spi_write (uint8_tchip_select, uint8_tchip_address, uint16_ttarget_register, int32_tvalue, uint8_treg_len)
Definition at line 221 of file spi_ade7880_protocol.c.
References address_byte_ut::address_all, ade7880_write_tx_buff_ut::address_byte, ADE7880_WR, address_byte_ut::bits, CHIP_ADDRESS1, DISABLE, ENABLE, LAST_ADD, LAST_OP, LAST_RWDATA16, LAST_RWDATA32, LAST_RWDATA8, address_byte_ut::RD_WR, ade7880_write_tx_buff_ut::reg16, ade7880_write_tx_buff_ut::reg32, ade7880_write_tx_buff_ut::reg8, spi_read(), value, and WR_MSG_LENGTH.
Referenced by main(), and wait_new_conversion().
                                                                                                                 {
      
      
    int8_t result = 0;
    ade7880_write_tx_buff_ut tx_buff;
     tx_buff.msg_fields.address_byte.address_all = chip_address;
     tx_buff.msg_fields.address_byte.bits.RD_WR = ADE7880_WR;
     tx_buff.msg_fields.target_register = htons(target_register);
     
    if(reg_len == sizeof(uint8_t))
      tx_buff.msg_fields.value.reg8 = (uint8_t)value;
    else if(reg_len == sizeof(uint16_t))
      tx_buff.msg_fields.value.reg16 = htons((uint16_t)value);
    else if(reg_len == sizeof(uint32_t))
      tx_buff.msg_fields.value.reg32 = htonl((uint32_t)value);
    
    #ifdef DEBUG
      if(debug_print&0x01){
       printf('\nMSG SENT: WR\n');
       printf(' Chip Address %02X\n',
       tx_buff.msg_fields.address_byte.address_all);
       printf(' Target Register %04X\n',
       ntohs(tx_buff.msg_fields.target_register));
       printf(' Value sent %08X\n',
       ntohl(tx_buff.msg_fields.value.reg32));
       }
    #endif
    bcm2835_spi_transfern(tx_buff.msg_all,WR_MSG_LENGTH + reg_len);
    
    
    uint8_t result8 =0;
    uint16_t result16 =0;
    int32_t result32 =0;
    
     #ifdef DEBUG
     if(!(debug_print&0x80))
     debug_print = DISABLE;
       printf('\nvarifying last operation ...\n');
     #endif
     if((result8 =(uint8_t)(spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,LAST_OP,sizeof(uint16_t))))
     !=0xCA /*LAST_OP!=WR*/){
             
     #ifdef DEBUG
       printf('\n <--- WR failure : LAST_OP \n');
       printf(' LAST_OP value :%02X\n',result8);
     #endif
     result = -1;
     }else{
      #ifdef DEBUG
       printf(' LAST_OP value :%02X\n',result8);
     #endif
     }
     
     #ifdef DEBUG
       printf('\nvarifying last accessed register ...\n');
     #endif
     if((result16 =(uint16_t)(spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,LAST_ADD,sizeof(uint16_t))))!=target_register){
             
     #ifdef DEBUG
       printf('\n <--- WR failure : LAST_ADD\n');
       printf(' Target Register :%04X\n', target_register);
       printf(' LAST_ADD value :%04X\n',result16);
     #endif
     result = -1;
     }else{
      #ifdef DEBUG
        printf(' LAST_ADD value :%04X\n',result16);
      #endif
     }
     
    
     #ifdef DEBUG
       printf('\nvarifying last accessed register value:\n');
     #endif
    if(reg_len == sizeof(uint8_t)){
        result32 = (int32_t)(spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,LAST_RWDATA8,sizeof(uint8_t))&0x000000FF);
    }else
    if(reg_len == sizeof(uint16_t)){
        result32 = (int32_t)(spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,LAST_RWDATA16,sizeof(uint16_t))&0x0000FFFF);
    }else
    if(reg_len == sizeof(uint32_t)){
        result32 = (int32_t)(spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,LAST_RWDATA32,sizeof(uint32_t)));
    }
    //if
     if(result32!=value)
         result = -1;
     #ifdef DEBUG
       if(result32!=value)
       printf('\n <--- WR failure : LAST_RWDATA\n');
       printf(' Sent Value :%08X\n', value);
       printf(' LAST_RWDATA value :%08X\n',result32);
      if(!(debug_print&0x80))
       debug_print = ENABLE;
     #endif
     
     
    return result;
}
Author
Generated automatically by Doxygen for EMS from the source code.