SERVICE
NAME
SERVICE -
float measure (uint8_t cmd, uint8_t channel, float samples)
.PP
 "
uint16_t hex2val (uint8_t cc)
.PP
 "
uint16_t make16 (uint8_t *buf, uint16_t idx)
.PP
 "
uint8_t make8 (uint8_t *buf, uint16_t idx)
.PP
 "
Detailed Description
SERVICE
This is service module containing recommended measurement reading
 procedures used when fetching measured data form ADE7880.And also,
 additional service functions used throught the program are included here
Function Documentation
uint16_t hex2val (uint8_tcc)
 Parameters:
cc Hexadecimal character value to be converted to integer
Function converts hex character to the corresponding integer value.
Returns:
on success returns the resulting 16 bit unsigned integer value.
Definition at line 165 of file srv_cmd_handler.c.
Referenced by make16(), and make8().
{
    return (uint16_t)(((cc >= '0' ) && (cc <= '9' )) ? (cc - '0') : (cc - 'A' + 10) );
     
}
uint16_t make16 (uint8_t *buf, uint16_tidx)
 Parameters:
buf pointer to Hexadecimal character buffer
idx index to first character of 16 bit hex number string
 (four charaters used).
Function converts string of hex character to the corresponding 16 bit unsigned integer value.
Returns:
on success returns the resulting 16 bit unsigned integer value.
Definition at line 185 of file srv_cmd_handler.c.
References hex2val().
Referenced by main().
{
    return ((hex2val(buf[idx+0])<<12)|(hex2val(buf[idx+1])<<8)|(hex2val(buf[idx+2])<<4)|(hex2val(buf[idx+3])<<0));
}
uint8_t make8 (uint8_t *buf, uint16_tidx)
 Parameters:
buf pointer to Hexadecimal character buffer
idx index to first character of 16 bit hex number string
 (two charaters used)
Function converts string of hex character to the corresponding 8 bit unsigned integer value.
Returns:
on success returns the resulting 8 bit unsigned integer value.
Definition at line 207 of file srv_cmd_handler.c.
References hex2val().
Referenced by main().
{
    return (uint8_t)((hex2val(buf[idx+0])<<4)|(hex2val(buf[idx+1]))<<0);
}
float measure (uint8_tcmd, uint8_tchannel, floatsamples)
 Parameters:
cmd Indicates the target register value to read
channel Indicates the target channel
samples Indicates the number of samples read by the function
The Function runs recommended reading procedures designed, to enhance the accuracy of measurements by taking the average of readings taken at different instance.
Returns:
on success returns the avarge of the measured value, on failure return -1 .
Definition at line 40 of file srv_cmd_handler.c.
References AIRMS, AVRMS, AWATT, AWATTHR, BIRMS, BVRMS, BWATT, BWATTHR, CHIP_ADDRESS1, CIRMS, CVRMS, CWATT, CWATTHR, ILSB_CONST, measure(), PHASE_A, PHASE_ACTIVE_POWER, PHASE_ACTIVE_WH, PHASE_B, PHASE_C, PHASE_IRMS, PHASE_VRMS, spi_read(), TOTAL_ACTIVE_POWER, TOTAL_ACTIVE_WH, TRANSFORMER_RATIO, VLSB_CONST, wait_new_conversion(), WATTLSB_CONST, and WHLSB_CONST.
Referenced by measure(), and reading_loop().
                                                        {
    float measured_val=0;
         switch(cmd)
        {
           
                case PHASE_VRMS:
                {
                                
                    uint16_t ii;
                    uint16_t target_reg = (channel==PHASE_A )?AVRMS
                                          :(channel==PHASE_B )?BVRMS
                                          :(channel==PHASE_C )?CVRMS
                                          :0;
                    
                    if(target_reg==0)return -1;
                    for(ii=0;ii<samples;ii++){
                    if(wait_new_conversion()==-1)return -1;
                    measured_val += (uint32_t)(spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,target_reg,sizeof(uint32_t))&0xFFFFFF)*TRANSFORMER_RATIO;
                    if(ii%50 == 0)printf('#\n');else printf('#');
                    }
                    measured_val /=samples;
                    
            
                    return measured_val/VLSB_CONST;
                
                }break;
                case PHASE_IRMS:
                {
                    uint16_t ii;
                    uint16_t target_reg = (channel==PHASE_A )?AIRMS
                                          :(channel==PHASE_B )?BIRMS
                                          :(channel==PHASE_C )?CIRMS
                                          :0;
                    if(target_reg==0)return -1;
                    for(ii=0;ii<samples;ii++){
                    if(wait_new_conversion()==-1)return -1;
                    measured_val += spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,target_reg,sizeof(uint32_t));
                    if(ii%50 == 0)printf('#\n');else printf('#');
                    
                    }
                    measured_val /=samples;
                    
                    return measured_val/ILSB_CONST;
                
                }break;
                
                
                case PHASE_ACTIVE_WH:/*considers also harmoics , trouble? then we change it to fundamental*/
                {
            
                    uint16_t target_reg = (channel==PHASE_A )?AWATTHR
                                          :(channel==PHASE_B )?BWATTHR
                                          :(channel==PHASE_C )?CWATTHR
                                          :0;
                                          
                    measured_val = spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,target_reg,sizeof(uint32_t));
                    printf('#');
                    return measured_val/WHLSB_CONST;
                
                }break;
                
                case TOTAL_ACTIVE_WH:/*considers also harmoics */
                {
                    
                    uint16_t target_reg = (channel==PHASE_A )?AWATTHR
                                          :(channel==PHASE_B )?BWATTHR
                                          :(channel==PHASE_C )?CWATTHR
                                          :0;
                    
                     return measure(PHASE_ACTIVE_WH,PHASE_A,1)
                            +measure(PHASE_ACTIVE_WH,PHASE_B,1)
                            +measure(PHASE_ACTIVE_WH,PHASE_C,1);
                     
                
                }break;
                
                case PHASE_ACTIVE_POWER:
                {
                    uint16_t target_reg = (channel==PHASE_A )?AWATT
                                            :(channel==PHASE_B )?BWATT
                                            :(channel==PHASE_C )?CWATT
                                            :0;
                                          
                    measured_val = spi_read(BCM2835_SPI_CS0,CHIP_ADDRESS1,target_reg,sizeof(uint32_t));
                    printf('#');
                    return measured_val/WATTLSB_CONST;
                    
                }break;
                
                case TOTAL_ACTIVE_POWER:
                {
                
                            
                     return measure(PHASE_ACTIVE_POWER,PHASE_A,1)
                            +measure(PHASE_ACTIVE_POWER,PHASE_B,1);
                            +measure(PHASE_ACTIVE_POWER,PHASE_C,1);
                    
                }break;
                
                default:
                {
                  // return -1;
                }break;
     
        }
}
Author
Generated automatically by Doxygen for EMS from the source code.