.TH "srv_cmd_handler.c" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srv_cmd_handler.c \- 
.PP
\fIFile:\fP \fBsrv_cmd_handler\&.c\fP 
.br
  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./includes/includes\&.h'\fP
.br

.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "float \fBmeasure\fP (uint8_t cmd, uint8_t channel, float samples)"
.br
.RI "\fI.PP
 \fP"
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "uint16_t \fBhex2val\fP (uint8_t cc)"
.br
.RI "\fI.PP
 \fP"
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "uint16_t \fBmake16\fP (uint8_t *buf, uint16_t idx)"
.br
.RI "\fI.PP
 \fP"
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "uint8_t \fBmake8\fP (uint8_t *buf, uint16_t idx)"
.br
.RI "\fI.PP
 \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
\fIFile:\fP \fBsrv_cmd_handler\&.c\fP 
.br
 

\fIPurpose:\fP 
.br
 
.PP
Definition in file \fBsrv_cmd_handler\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EMS from the source code\&.
