.TH "status1_reg_u" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
status1_reg_u \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ade7880_registers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBreg_all\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBbits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 266 of file ade7880_registers\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. }  bits"

.SS "uint32_t reg_all"

.PP
Definition at line 268 of file ade7880_registers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMS from the source code\&.
