.TH "value_ut" 3 "Mon Feb 24 2014" "Version V1" "EMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
value_ut \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spi_ade7880_protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBreg8\fP"
.br
.ti -1c
.RI "uint16_t \fBreg16\fP"
.br
.ti -1c
.RI "uint32_t \fBreg32\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file spi_ade7880_protocol\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t reg16"

.PP
Definition at line 34 of file spi_ade7880_protocol\&.h\&.
.SS "uint32_t reg32"

.PP
Definition at line 35 of file spi_ade7880_protocol\&.h\&.
.SS "uint8_t reg8"

.PP
Definition at line 33 of file spi_ade7880_protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMS from the source code\&.
